name: CI pipeline

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]
    workflow_dispatch:

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    avoid-redundancy:
        runs-on: ubuntu-22.04
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.10.0
              with:
                  access_token: ${{ github.token }}

    lint:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'
            - run: pnpm install --frozen-lockfile
            - uses: trunk-io/trunk-action@v1

    check-web-changed:
        runs-on: ubuntu-22.04
        outputs:
            web_changed: ${{ steps.check-web-changed.outputs.web_changed }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - shell: pwsh
              id: check-web-changed
              run: |
                  $diff = git diff --name-only HEAD^ HEAD
                  $SourceDiff = $diff | Where-Object { $_ -match '^apps/web' }
                  $HasDiff = $SourceDiff.Length -gt 0
                  Write-Host "::set-output name=web_changed::$HasDiff"

    build-web:
        runs-on: ubuntu-22.04
        needs: [check-web-changed]
        if: needs.check-web-changed.outputs.web_changed == 'true'
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'
            - run: |
                  pnpm install --frozen-lockfile
                  pnpm build:web
